name: Deploying Simple Website to Ec2 Using Ansible

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
      - name: Terraform apply
        working-directory: terraform
        run: terraform apply --auto-approve
      - name: Get Terraform Outputs
        working-directory: terraform
        run: |
          echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
          terraform output -raw private_key > ../ansible-key.pem
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          mv ansible-key.pem ~/.ssh/ansible-key.pem
          chmod 600 ~/.ssh/ansible-key.pem
          ssh-keyscan -H "${{ env.PUBLIC_IP }}" >> ~/.ssh/known_hosts
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install ansible -y
      - name: Create Ansible Inventory
        working-directory: ansible
        run: |
          key_path="$HOME/.ssh/ansible-key.pem"
          cat > inventory <<EOF
          [webservers]
          $PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=$key_path
          EOF
      - name: Wait for EC2 SSH
        run: |
          echo "Waiting for EC2 to become reachable..."
          until ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ansible-key.pem \
            ubuntu@$PUBLIC_IP "echo Connected" >/dev/null 2>&1
          do
            sleep 10
          done
      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -i inventory test.yaml
        env:
          AWS_DEFAULT_REGION: ap-southeast-1
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PUBLIC_IP: ${{ env.PUBLIC_IP }}
